// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Area } from "./../../utils/AreaUtils.sol";

/**
 * @title IAdminSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAdminSystem {
  function deathmatch__startGame(uint256 numBlocksToEnd) external;

  function deathmatch__setMatchArea(string memory name, Area memory area) external;

  function deathmatch__setJoinFee(uint256 newJoinFee) external;
}
