// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Area } from "./../../utils/AreaUtils.sol";

/**
 * @title IExperienceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IExperienceSystem {
  function racetothesky__joinExperience() external payable;

  function racetothesky__initExperience() external;

  function racetothesky__resetGame(string memory name, Area memory area) external payable;
}
