// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { LeaderboardEntry } from "./../../Types.sol";

/**
 * @title IExperienceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IExperienceSystem {
  function deathmatch__joinExperience() external payable;

  function deathmatch__initExperience() external;

  function deathmatch__claimRewardPool() external;

  function deathmatch__getKillsLeaderboard() external view returns (LeaderboardEntry[] memory);
}
