// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IExperienceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IExperienceSystem {
  function bountyhunter__joinExperience() external payable;

  function bountyhunter__initExperience() external;

  function bountyhunter__withdraw() external;
}
